C4Context
  title System Context diagram for Internet Banking System
  Person(customerA, "Banking Customer", "A customer of the bank.")
  System(SystemAA, "Internet Banking System", "Allows customers to view information.")

  Rel(customerA, SystemAA, "Uses")
